# Generated by Django 4.2.1 on 2023-05-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('PlayerID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=1000)),
                ('TeamName', models.CharField(max_length=1000)),
                ('FantasyPoints', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
            ],
        ),
    ]
